version: "3.9"

services:
  postgres_db:
    image: postgres
    restart: always
    command: -p 5431
    env_file:
      - .env
    expose:
      - 5431
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis_db:
    image: redis
    restart: always
    expose:
      - 6388
    ports:
      - "6388:6388"
    volumes:
        - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6388
  web:
    depends_on:
      - postgres_db
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8020
    env_file:
      -  .env
    ports:
      - "8001:8020"
    volumes:
      - ./staticfiles:/app/staticfiles/

volumes:
  postgres_data:
  redis_data: 